### PR TITLE
DEPENDENCY: upgrade to ember v3.1.1

### PR DESCRIPTION
**Pull request by toranb**
@nchristus huge upgrade here ;) but pushing ahead to ember v3.1.1+

I plan to do a major NPM version bump tomorrow as users will need to slowly migrate away from legacy actions. I've included support for closure actions for those who have the time to start migrating over. I don't plan to remove classic/legacy action support for a good year or so but this should give people the ability to move forward.

Any questions or issues with this before I merge/kick out a new major release tomorrow morning?

### CODE REVIEW

**Comment by nchristus** [comment]
Should we bump the version in package.json?

Also, thank you for the work to upgrade this.

**Comment by gion-andri** [comment]
I tested this change, everything seems still to work smoothly. 

Thank you very much for all your work!

**Comment by toranb** [comment]
@nchristus I'll do the package.json version bump after this lands. I did spend some time last night trying to upgrade the linked ember-cli-test-helpers addon but its clear that addon needs a more serious time investment /and likely a handful of deprecations to migrate it.

I've cut out the need to use that addon because it turns out we only needed 3 of the helper functions it provided anyway. I've also added a deprecation warning for the legacy (non closure) action type to alert people that they should migrate toward closure actions at some point.

**Comment by toranb** [comment]
@gion-andri this is now up on npm as `v3.0.0`

let me know if you bump into any problems w/ the released version ;)

@nchristus if you are still using this on any personal/or work projects let me know if the upgrade goes smoothly when you get time to try it out.

**Comment by nchristus** [comment]
@toranb will do. thank you, sir!

**Pull request merged**
