### PR TITLE
Add syntax highlighting to README

### PR DESCRIPTION
**Pull request by ryanponce**

### CODE REVIEW

**Comment by toranb** [comment]
Looks like we need to set the node version to 4 or 6 to fix the build first (travis yml)

Can you update this as part of the PR?

**Comment by toranb** [comment]
Awesome! Thank you

**Comment by ryanponce** [comment]
No problemo.

**Comment by toranb** [comment]
@nchristus I'll wait for you to approve/merge/publish this boss man ;)

**Pull request merged**
