### PR TITLE
[UPGRADE and FEATURE] upgraded ember-cli -> 0.2.3 and added ability to set inputId

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by williamsbdev** [comment]
if the inputId is not a desired feature, we can just revert the [FEATURE] commit. Thanks!

**Comment by toranb** [comment]
This looks great @williamsbdev - the only question I have is "what happens when I don't include the id" ? I assume a simple test case would prove it just produces nothing ?

**Comment by williamsbdev** [comment]
Good question. I will add a test for that this weekend.

**Comment by williamsbdev** [comment]
It looks like when you don't provide an `id`, it will have the default ember generated id.

**Comment by toranb** [comment]
Perfect !

**Comment by toranb** [comment]
Just did the npm publish - now version 1.2.0 is live (sorry for the delay on this)

**Pull request merged**
